import { IncomeType } from '../../../../core/models/income.model';

/**
 * Per-income-type field visibility map. Each type lists the field keys that
 * are relevant to it; everything else is hidden. This is what makes the form
 * reshape itself when the user changes the income type.
 *
 * Recurrence-driven fields (start_date, end_date, day_of_month, auto_add) are
 * layered on top of these by the recurrence rules and only appear when the
 * income actually repeats.
 */
export const TYPE_FIELD_MAP: Record<IncomeType, string[]> = {
  salary: [
    'title',
    'amount',
    'currency',
    'income_type',
    'recurrence',
    'status',
    'payment_date',
    'payment_time',
    'employer',
    'payment_mode',
    'category_id',
    'source_id',
    'is_taxable',
    'tag_ids',
    'notes',
  ],
  freelance: [
    'title',
    'amount',
    'currency',
    'income_type',
    'recurrence',
    'status',
    'payment_date',
    'payment_time',
    'client',
    'platform',
    'project_name',
    'payment_mode',
    'category_id',
    'source_id',
    'is_taxable',
    'tag_ids',
    'notes',
  ],
  bonus: [
    'title',
    'amount',
    'currency',
    'income_type',
    'status',
    'payment_date',
    'payment_time',
    'employer',
    'payment_mode',
    'is_taxable',
    'tag_ids',
    'notes',
  ],
  commission: [
    'title',
    'amount',
    'currency',
    'income_type',
    'status',
    'payment_date',
    'client',
    'platform',
    'payment_mode',
    'is_taxable',
    'tag_ids',
    'notes',
  ],
  gift: [
    'title',
    'amount',
    'currency',
    'income_type',
    'status',
    'payment_date',
    'payment_mode',
    'tag_ids',
    'notes',
  ],
  dividend: [
    'title',
    'amount',
    'currency',
    'income_type',
    'recurrence',
    'status',
    'payment_date',
    'platform',
    'reference_number',
    'payment_mode',
    'is_taxable',
    'tag_ids',
    'notes',
  ],
  business: [
    'title',
    'amount',
    'currency',
    'income_type',
    'recurrence',
    'status',
    'payment_date',
    'client',
    'project_name',
    'reference_number',
    'payment_mode',
    'category_id',
    'source_id',
    'is_taxable',
    'tag_ids',
    'notes',
  ],
  one_time: [
    'title',
    'amount',
    'currency',
    'income_type',
    'status',
    'payment_date',
    'payment_time',
    'payment_mode',
    'category_id',
    'source_id',
    'is_taxable',
    'tag_ids',
    'notes',
  ],
  custom: [
    'title',
    'amount',
    'currency',
    'income_type',
    'recurrence',
    'status',
    'payment_date',
    'payment_time',
    'employer',
    'client',
    'platform',
    'project_name',
    'reference_number',
    'payment_mode',
    'category_id',
    'source_id',
    'is_taxable',
    'tag_ids',
    'notes',
  ],
};

/** Income types that may be configured as auto-recurring salary-style income. */
export const AUTO_RECURRING_TYPES: IncomeType[] = ['salary', 'dividend', 'business', 'custom'];
